import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
size = 13

[window]
opacity = 0.94
blur = true

[env]
TERM = "xterm-256color"
